<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator._jJoFt.' shared service.

return $this->privates['.service_locator._jJoFt.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'tag' => ['privates', '.errored..service_locator._jJoFt..App\\Entity\\Tags', NULL, 'Cannot autowire service ".service_locator._jJoFt.": it references class "App\\Entity\\Tags" but no such service exists.'],
]);
