<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.errored..service_locator.03Y_XGM.Symfony\Component\Form\FormFactory' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormFactoryInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\form\\FormFactory.php';

return $this->privates['.errored..service_locator.03Y_XGM.Symfony\Component\Form\FormFactory'] = new \Symfony\Component\Form\FormFactory();
