<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.bzKUs.S' shared service.

return $this->privates['.service_locator.bzKUs.S'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'film' => ['privates', '.errored..service_locator.bzKUs.S.App\\Entity\\Films', NULL, 'Cannot autowire service ".service_locator.bzKUs.S": it references class "App\\Entity\\Films" but no such service exists.'],
]);
