<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.a3EIJcY' shared service.

return $this->privates['.service_locator.a3EIJcY'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'creature' => ['privates', '.errored..service_locator.a3EIJcY.App\\Entity\\Creatures', NULL, 'Cannot autowire service ".service_locator.a3EIJcY": it references class "App\\Entity\\Creatures" but no such service exists.'],
]);
