<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private '.service_locator.TlXOMz0' shared service.

return $this->privates['.service_locator.TlXOMz0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'page' => ['privates', '.errored..service_locator.TlXOMz0.App\\Entity\\Pages', NULL, 'Cannot autowire service ".service_locator.TlXOMz0": it references class "App\\Entity\\Pages" but no such service exists.'],
]);
