<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'debug.argument_resolver.service' shared service.

include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\TraceableValueResolver.php';
include_once $this->targetDirs[3].'\\vendor\\symfony\\http-kernel\\Controller\\ArgumentResolver\\ServiceValueResolver.php';

return $this->privates['debug.argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\TraceableValueResolver(new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($this->getService, [
    'App\\Controller\\CreaturesController::delete' => ['privates', '.service_locator.a3EIJcY', 'get_ServiceLocator_A3EIJcYService.php', true],
    'App\\Controller\\CreaturesController::edit' => ['privates', '.service_locator.a3EIJcY', 'get_ServiceLocator_A3EIJcYService.php', true],
    'App\\Controller\\CreaturesController::show' => ['privates', '.service_locator.a3EIJcY', 'get_ServiceLocator_A3EIJcYService.php', true],
    'App\\Controller\\FilmsController::show' => ['privates', '.service_locator.bzKUs.S', 'get_ServiceLocator_BzKUs_SService.php', true],
    'App\\Controller\\PagesController::show' => ['privates', '.service_locator.TlXOMz0', 'get_ServiceLocator_TlXOMz0Service.php', true],
    'App\\Controller\\TagsController::show' => ['privates', '.service_locator._jJoFt.', 'get_ServiceLocator_JJoFt_Service.php', true],
    'App\\Controller\\CreaturesController:delete' => ['privates', '.service_locator.a3EIJcY', 'get_ServiceLocator_A3EIJcYService.php', true],
    'App\\Controller\\CreaturesController:edit' => ['privates', '.service_locator.a3EIJcY', 'get_ServiceLocator_A3EIJcYService.php', true],
    'App\\Controller\\CreaturesController:show' => ['privates', '.service_locator.a3EIJcY', 'get_ServiceLocator_A3EIJcYService.php', true],
    'App\\Controller\\FilmsController:show' => ['privates', '.service_locator.bzKUs.S', 'get_ServiceLocator_BzKUs_SService.php', true],
    'App\\Controller\\PagesController:show' => ['privates', '.service_locator.TlXOMz0', 'get_ServiceLocator_TlXOMz0Service.php', true],
    'App\\Controller\\TagsController:show' => ['privates', '.service_locator._jJoFt.', 'get_ServiceLocator_JJoFt_Service.php', true],
])), ($this->privates['debug.stopwatch'] ?? ($this->privates['debug.stopwatch'] = new \Symfony\Component\Stopwatch\Stopwatch(true))));
