<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHC9axGb\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHC9axGb/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHC9axGb.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHC9axGb\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerHC9axGb\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'HC9axGb',
    'container.build_id' => '7b4e5ffd',
    'container.build_time' => 1554659189,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHC9axGb');
